---
log.level: debug
http.host: "0.0.0.0"
path.config: /usr/share/logstash/pipeline
# automatic reloading will not work with stdin input
config.reload.automatic: false
pipeline.ecs_compatibility: disabled
# For easier testing of batches with multiple messages we use longer delay
pipeline.batch.delay: 5000
